#!/usr/bin/env bash
self_path=$(realpath "${BASH_SOURCE[0]}")
self_dir=$(dirname "$self_path")
.   "$self_dir/common"

opt_pid=
while (( $# )); do
    case $1 in
        -p)
            opt_pid="$2"
            shift
            ;;
        *)  break;;
    esac
    shift
done

write_file $tracing_dir/current_tracer function
run_at_exit "write_file $tracing_dir/current_tracer nop"

if [[ -n "$opt_pid" ]]; then
    write_file $tracing_dir/set_ftrace_pid "$opt_pid"
    run_at_exit "write_file $tracing_dir/set_ftrace_pid"
fi

write_file $tracing_dir/tracing_on 1
run_at_exit "write_file $tracing_dir/tracing_on 0"

cat $tracing_dir/trace_pipe

