#!/bin/bash
set -e

self_path=$(realpath "${BASH_SOURCE[0]}")
proj_prefix=$(dirname "$(dirname "$self_path")")
.   "$proj_prefix/utils/common.sh"

base_dir="/sys/kernel/tracing"

opt_pid=
opt_options=
while (( $# )); do
    case $1 in
        -p)
            opt_pid="$2"
            shift
            ;;
        -o)
            opt_options+=" $2"
            shift
            ;;
        *)  break;;
    esac
    shift
done

run_at_exit "write_file $base_dir/current_tracer $(cat $base_dir/current_tracer)"
write_file $base_dir/current_tracer function

if [[ -n "$opt_pid" ]]; then
    run_at_exit "write_file $base_dir/set_ftrace_pid"
    write_file $base_dir/set_ftrace_pid "$opt_pid"
fi

if [[ -n "$opt_options" ]]; then
    run_at_exit "write_file $base_dir/trace_options $(cat $base_dir/trace_options)"
    write_file $base_dir/trace_options $opt_options
fi

run_at_exit "write_file $base_dir/tracing_on $(cat $base_dir/tracing_on)"
write_file $base_dir/tracing_on 1

cat $base_dir/trace_pipe

