#!/bin/bash
set -e

self_path=$(realpath "${BASH_SOURCE[0]}")
proj_prefix=$(dirname "$(dirname "$self_path")")
.   "$proj_prefix/utils/common.sh"

base_dir="/sys/kernel/tracing"

run_at_exit "write_file $base_dir/current_tracer $(cat $base_dir/current_tracer)"
write_file $base_dir/current_tracer function_graph

run_at_exit "write_file $base_dir/tracing_on $(cat $base_dir/tracing_on)"
write_file $base_dir/tracing_on 1

cat $base_dir/trace_pipe

