#!/usr/bin/env bash
set -e

self_dir=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
.   "$self_dir/common"

do_main() {
    for t in "$@"; do
        do_kprobe_enabled "$t"
    done
}

main "$@"

