#!/usr/bin/env bash
set -e

self_path=$(realpath "${BASH_SOURCE[0]}")
proj_prefix=$(dirname "$(dirname "$self_path")")
.   "$proj_prefix/utils/common.sh"

base_dir="/sys/kernel/tracing"

run_at_exit "write_file $base_dir/kprobe_events -:sys_open_probe"
echo "p:sys_open_probe do_sys_openat2 +0(\$arg2):string" >> $base_dir/kprobe_events
run_at_exit "write_file $base_dir/events/kprobes/sys_open_probe/enable 0"
echo 1 > $base_dir/events/kprobes/sys_open_probe/enable

run_at_exit "write_file $base_dir/kprobe_events -:sys_open_retprobe"
echo "r:sys_open_retprobe do_sys_openat2 \$retval" >> $base_dir/kprobe_events
run_at_exit "write_file $base_dir/events/kprobes/sys_open_retprobe/enable 0"
echo 1 > $base_dir/events/kprobes/sys_open_retprobe/enable

run_at_exit "write_file $base_dir/tracing_on 0"
write_file $base_dir/tracing_on 1

cat $base_dir/trace_pipe

