#!/usr/bin/env bash
set -euxo pipefail

die() {
    echo "$@"
    exit 1
}

exit_hooks=()
run_atexit() {
    exit_hooks+=("$*")
}
atexit() {
    for ((i = ${#exit_hooks[@]} - 1; i >= 0; i--)); do
        if ! eval ${exit_hooks[$i]}; then
            die "WARNING: command failed \"${exit_hooks[$i]}\""
        fi
    done
}
trap 'atexit' EXIT

tracing_dir="/sys/kernel/tracing"
[[ ! -d $tracing_dir ]] && die "tracefs not mount"

do_kprobe() {
    name="${1#*:}"
    echo "$1 $2 $3" >> $tracing_dir/kprobe_events
    run_atexit "echo -:${name} >> $tracing_dir/kprobe_events"

    echo 1 > $tracing_dir/events/kprobes/${name}/enable
    run_atexit "echo 0 > $tracing_dir/events/kprobes/${name}/enable"
}

do_kprobe 'p:do_sys_openat2' 'do_sys_openat2' '+0($arg2):string'

echo 1 > $tracing_dir/tracing_on
run_atexit "echo 0 > $tracing_dir/tracing_on"
cat $tracing_dir/trace_pipe

