#!/usr/bin/env bash
set -xe

self_dir=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
.   "$self_dir/common"

[ -e "$tracefs/events/kprobes" ] && do_run "echo 0 > '$tracefs/events/kprobes/enable'"
echo > "$tracefs/kprobe_events"

echo nop > "$tracefs/current_tracer"
echo 0 > "$tracefs/tracing_on"

