#!/usr/bin/env bash
set -euxo pipefail

die() {
    echo "$@"
    exit 1
}

exit_hooks=()
run_atexit() {
    exit_hooks+=("$*")
}
atexit() {
    for ((i = ${#exit_hooks[@]} - 1; i >= 0; i--)); do
        if ! eval ${exit_hooks[$i]}; then
            die "WARNING: command failed \"${exit_hooks[$i]}\""
        fi
    done
}
trap 'atexit' EXIT

tracing_dir="/sys/kernel/tracing"
[[ ! -d $tracing_dir ]] && die "tracefs not mount"

[ -w $tracing_dir/events/kprobes/enable ] && echo 0 > $tracing_dir/events/kprobes/enable
echo > $tracing_dir/kprobe_events
echo 0 > $tracing_dir/tracing_on
echo nop $tracing_dir/current_tracer

