#!/usr/bin/env bash
set -e

self_dir=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
.   "$self_dir/common"

do_main() {
    do_uprobe_enabled "$@"
    init_event_options "$@"
}

main "$@"


